#
- name: Install base packages from yum
  import_tasks: yum.yml
  tags:
    - prod
  become: yes

- name: Install CentOS 6 packages
  import_tasks: docker_c6.yml
  when: >
        ansible_distribution == 'CentOS'
        and ansible_distribution_major_version == '6'
  tags:
    - prod
  become: yes

- name: Install CentOS 7 packages
  import_tasks: docker_c7.yml
  when: >
        ansible_distribution == 'CentOS'
        and ansible_distribution_major_version == '7'
  tags:
    - prod
  become: yes

- name: Install docker-compose
  import_tasks: docker_compose.yml
  tags:
    - prod
  become: yes

