#
- name: Remove existing docker
  yum: 
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - docker-engine
  tags:
    - prod
  become: yes

- name: install basic packages with yum
  yum: 
    name: "{{ item }}"
    state: latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  tags:
    - prod
  become: yes
